---
name: Matthew
surname: Barnfield
position: "Postdoctoral Fellow"
www: matthewbarnfield.co.uk
header-includes: 
   - \usepackage{times}
font-family: Times New Roman
mainfont: Times New Roman
email: "m.g.barnfield@gmail.com"
twitter: m_barnfield
github: mbarnfield
output: 
  vitae::moderncv:
    theme: classic
headcolor: "100088"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Employment

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Mark,
  "ESRC Postdoctoral Fellow", "2022-2023", "University of Essex", "Department of Government",
  "Postdoctoral Research Fellow", "2021-2022", "University of Exeter", "Department of Politics"
) %>% 
  detailed_entries(Degree, Year, Institution, Mark)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Mark,
  "PhD Political Science", "2018-2021", "Queen Mary University of London", "supervised by Professor Philip Cowley and Dr Javier Sajuria, examined by Professor Shaun Bowler and Dr James Strong. Funded by ESRC. Awarded PSA McDougall Trust Dissertation Prize",
  "MRes Politics and International Relations", "2017-2018", "University of Bath", "Distinction",
  "BA Modern Languages and European Studies", "2013-2017", "University of Bath", "First-class Hons. Awarded Gordon Horner Prize for highest overall performance on degree programme"
) %>% 
  detailed_entries(Degree, Year, Institution, Mark)
```



# Research

## Awards (funds and prizes)

```{r}
library(tibble)
tribble(
  ~ Name, ~ Year, ~ From, ~Value,
  "ESRC Postdoctoral Fellowship", "2022", "SeNSS Doctoral Training Partnership", "£124,161", 
  "McDougall Trust Dissertation Prize", "2022", "Political Studies Association", "",
  "YouGov Survey Questions Grant", "2022", "EPOP Specialist Group", "approx. £1,000", 
  "Postgraduate Research Fund", "2021", "Queen Mary University of London",  "£720", 
  "ESRC PhD Studentship", "2018", "LISS Doctoral Training Partnership", "approx. £66,000"
) %>% 
  detailed_entries(Name, Year, From, Value, .protect = FALSE)


```

## Journal articles

```{r}
library(tibble)
tribble(
  ~ Authors, ~ Order, ~ Title, ~ Journal,
  "Barnfield, M.", "2022", "Misinformation in Experimental Political Science", "\\href{https://www.cambridge.org/core/journals/perspectives-on-politics/article/misinformation-in-experimental-political-science/3A7A0F8F48C863C57C4AED4D54424E28}{Perspectives on Politics}",
  "Barnfield, M. and Bale, T.", "2022", "‘Leaving the red Tories’: ideology, leaders, and why party members quit", "\\href{https://journals.sagepub.com/doi/full/10.1177/1354068820962035}{Party Politics}",
  "Stöckli, S., Spälti, A. K., Phillips, J., Stoeckel, F., Barnfield, M., Thompson, J., Lyons, B., Mérola, V., Szewach, P., and Reifler, J.", "2022", "Which vaccine attributes foster vaccine uptake? A cross-country conjoint experiment", "\\href{https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0266003}{PLOS One}", 
  "Stoeckel, F., Stöckli, S., Phillips, J., Lyons, B., Mérola, V., Barnfield, M., Szewach, P., Thompson, J., and Reifler, J.", "2022", "Stamping the vaccine passport? Public support for lifting COVID-19 related restrictions for vaccinated citizens in France, Germany, and Sweden", "\\href{https://www.sciencedirect.com/science/article/pii/S0264410X22009653}{Vaccine}",
  "Zerback, T., Reinemann, C., and Barnfield, M.", "2021", "Total Recall? Examining the accuracy of poll recall during an election campaign", "\\href{https://www.tandfonline.com/doi/full/10.1080/15205436.2021.1936559}{Mass Communication and Society}",
  "Barnfield, M.", "2019", "Think Twice before Jumping on the Bandwagon: Clarifying Concepts in Research on the Bandwagon Effect", "\\href{https://journals.sagepub.com/doi/full/10.1177/1478929919870691}{Political Studies Review}",
) %>% 
  detailed_entries(Authors, Order, Title, Journal, .protect = FALSE)


```


## Blog posts

```{r}
library(tibble)
tribble(
  ~ Authors, ~ Order, ~ Title, ~ Journal,
    "Barnfield, M.", "2022", "Against misinformation as method in political science", "\\href{https://theloop.ecpr.eu/against-misinformation-as-method-in-political-science/}{The Loop}",
  "Bailey, J., and Barnfield, M.", "2021", "Vaccine bounce: why we should take it with a pinch of salt", "\\href{https://ukandeu.ac.uk/vaccine-bounce-why-we-should-take-it-with-a-pinch-of-salt/}{UK in a Changing Europe}"
) %>% 
  detailed_entries(Authors, Order, Title, Journal, .protect = FALSE)


```


# Teaching

```{r}
tribble(
  ~ Role, ~Name, ~ Date, ~ Place,
  "Teaching Associate", "POLM083: Introduction to Quantitative Methods (Postgraduate), POL269: Political Data Research, POL252: Political Research, POL112: Introduction into Politics", "2019-2021", "Queen Mary University of London",
) %>% 
  detailed_entries(Role, Date, Place, Name, .protect = FALSE)


```   


# Professional service 


```{r}
tribble(
  ~ Date, ~ Details, ~ Summary,
  "2019-present", "Peer reviewer", "British Journal of Political Science, Electoral Studies, Journal of Elections, Public Opinion, and Parties, Journal of Social and Political Psychology, Party Politics, PLOS One, Journal of Conflict Resolution",
  "2019-present", "Member", "Political Studies Association, EPOP Specialist Group, European Consortium for Political Research",
  "2019-2020", "Research Assistant", "ESRC Party Members Project"
) %>% 
  detailed_entries(Details, Date, Summary, .protect = FALSE)


``` 




