---
name: Matthew
surname: Barnfield
position: "PhD Candidate"
address: "School of Politics and International Relations"
phone: +44 7795247782
www: mbarnfield.github.io
email: "m.barnfield@qmul.ac.uk"
twitter: m_barnfield
github: mbarnfield
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "BA Modern Languages and European Studies", "2013-2017", "University of Bath", "Bath, UK",
  "MRes Politics and International Relations", "2017-2018", "University of Bath", "Bath, UK",
  "PhD Political Science", "2018-2021", "Queen Mary University of London", "London, UK"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
scholar::get_publications("EmD_lTEAAAAJ&EmD_lTEAAAAJ&") %>% 
  filter(cites > 30) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("curie.bib")

bibliography_entries("curie.bib")
```

